# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Gabriel Gularte <ggularte@3c.gg>, 2023.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-10-20 21:09-0300\n"
"PO-Revision-Date: 2023-10-20 21:15-0300\n"
"Last-Translator: Anonymous User <dev@3c.gg>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Translated-Using: django-rosetta 0.9.9\n"

#: accounts/admin.py:190
msgid "ACCOUNT"
msgstr "CONTA"

#: accounts/admin.py:200
msgid "IMPORTANT DATES"
msgstr "DATAS IMPORTANTES"

#: accounts/admin.py:201
msgid "PROFILE"
msgstr "PERFIL"

#: accounts/admin.py:203
msgid "STATUSES"
msgstr "STATUS"

#: accounts/admin.py:215
msgid "ACTIVATION"
msgstr "ATIVAÇÃO"

#: accounts/admin.py:304
msgid "Assume Identity"
msgstr "Assumir Identidade"

#: accounts/admin.py:305
msgid "Assume a user identity and use the application as the user"
msgstr ""
"Assuma a identidade de um usuário e utiliza a aplicação como se fosse ele"

#: accounts/api/controller.py:142
msgid "User already has an account."
msgstr "Usuário já possui uma conta."

#: accounts/api/controller.py:149 lobbies/models/lobby.py:325
msgid "User must be invited."
msgstr "Usuário deve ser convidado."

#: accounts/api/controller.py:182 accounts/api/schemas.py:174
msgid "Invalid verification token."
msgstr "Código de verificação inválido."

#: accounts/api/schemas.py:137 accounts/api/schemas.py:184
msgid "E-mail must be unique."
msgstr "O e-mail informado já está sendo utilizado."

#: accounts/api/schemas.py:142 accounts/api/schemas.py:147
msgid "User must read and agree with our Terms and Policy."
msgstr ""
"Usuário precisa ler e aceitar os Termos de Uso e a Política de Privacidade."

#: accounts/api/schemas.py:166
msgid "One of e-mail or verification_token must have a value."
msgstr "É preciso informar ao menos o e-mail ou o código de verificação."

#: accounts/api/schemas.py:194
#| msgid "User already invited."
msgid "User already invited by someone else."
msgstr "Usuário já foi convidado."

#: accounts/api/schemas.py:197
#| msgid "User already invited."
msgid "User has already been registered."
msgstr "Usuário já se cadastrou."

#: accounts/models/account.py:158
msgid "Steam account not found."
msgstr "Conta Steam não encontrada."

#: accounts/models/account.py:183
msgid "User should not be in more than one match."
msgstr "Usuário não pode estar em mais de uma partida ao mesmo tempo."

#: accounts/models/account.py:336
#, python-brace-format
msgid "Maximum invites reached ({self.MAX_INVITES_PER_ACCOUNT})."
msgstr "Máximo número de convites atingido ({self.MAX_INVITES_PER_ACCOUNT})."

#: accounts/models/account.py:340
msgid "Accepted invites cannot be modified."
msgstr "Convites aceitos não podem ser modificados."

#: accounts/models/account.py:343
msgid "An invite already exists for this email."
msgstr "Já existe um convite para este e-mail."

#: accounts/utils.py:101
msgid "Level points should never exceed max level points."
msgstr ""
"Pontos de nível ganhos nunca devem exceder o número máximo permitido de "
"Pontos de nível."

#: appsettings/forms.py:17
msgid "value is not integer"
msgstr "O valor não é um inteiro válido."

#: appsettings/forms.py:20
msgid "value is not boolean"
msgstr "O valor não é um boleano válido."

#: appsettings/models.py:21
msgid "Text"
msgstr "Texto"

#: appsettings/models.py:22
msgid "Integer"
msgstr "Inteiro"

#: appsettings/models.py:23
msgid "Boolean"
msgstr "Boleano"

#: appsettings/models.py:64
msgid ""
"We're about to start a maintenance. All queues and invites will be disabled."
msgstr ""
"Estamos iniciando uma manutenção. As filas e convites de lobby serão "
"desativados temporariamente."

#: appsettings/models.py:74
msgid "The maintenance is over. Queues and invites were enabled again. GLHF!"
msgstr ""
"A manutenção foi finalizada. Filas e convites de lobby estão habilitados "
"novamente. GLHF!"

#: core/api/pydantic_messages.py:4
msgid "field required"
msgstr "Esse campo é obrigatório."

#: core/api/pydantic_messages.py:5
msgid "extra fields not permitted"
msgstr "Campos extras não são permitidos nesse contexto."

#: core/api/pydantic_messages.py:6
msgid "none is not an allowed value"
msgstr "Vazio ou nulo não é um valor permitido."

#: core/api/pydantic_messages.py:7
msgid "value is not none"
msgstr "Valor é não nulo."

#: core/api/pydantic_messages.py:8
msgid "value is not None"
msgstr "Valor é não nulo."

#: core/api/pydantic_messages.py:10
msgid "value could not be parsed to a boolean"
msgstr "O valor não pode ser convertido para boleano."

#: core/api/pydantic_messages.py:12
msgid "byte type expected"
msgstr "O tipo esperado é \"byte\"."

#: core/api/pydantic_messages.py:13
msgid "value is not a valid dict"
msgstr "O valor não é um dicionário válido."

#: core/api/pydantic_messages.py:14
msgid "value is not a valid email address"
msgstr "O valor não é endereço de e-mail válido."

#: core/api/pydantic_messages.py:15
msgid "invalid or missing URL scheme"
msgstr "Esquema URL está faltando ou é inválido."

#: core/api/pydantic_messages.py:16
msgid "URL scheme not permitted"
msgstr "Esquema URL não permitido."

#: core/api/pydantic_messages.py:17
msgid "userinfo required in URL but missing"
msgstr "\"userinfo\" é obrigatório na URL."

#: core/api/pydantic_messages.py:18
msgid "URL host invalid"
msgstr "Host URL inválido."

#: core/api/pydantic_messages.py:20
msgid "URL host invalid, top level domain required"
msgstr "Host URL inválido."

#: core/api/pydantic_messages.py:23
msgid "URL port invalid, port cannot exceed 65535"
msgstr "Host URL inválido."

#: core/api/pydantic_messages.py:26
msgid "URL invalid, extra characters found after valid URL: {}"
msgstr "URL é inválida."

#: core/api/pydantic_messages.py:28
msgid "{} is not a valid Enum instance"
msgstr "{} não é uma instância \"Enum\" válida."

#: core/api/pydantic_messages.py:29
msgid "{} is not a valid IntEnum instance"
msgstr "{} não é uma instância \"IntEnum\" válida."

#: core/api/pydantic_messages.py:30
msgid "value is not a valid integer"
msgstr "O valor não é um inteiro válido."

#: core/api/pydantic_messages.py:31
msgid "value is not a valid float"
msgstr "O valor não é um \"float\" válido."

#: core/api/pydantic_messages.py:32
msgid "value is not a valid path"
msgstr "O valor não é um caminho válido."

#: core/api/pydantic_messages.py:34
msgid "file or directory at path \"{}\" does not exist"
msgstr "O arquivo ou diretório em \"{}\" não existe."

#: core/api/pydantic_messages.py:36
msgid "path \"{}\" does not point to a file"
msgstr "O caminho \"{}\" não representa um arquivo."

#: core/api/pydantic_messages.py:38
msgid "path \"{}\" does not point to a directory"
msgstr "O caminho \"{}\" não representa um diretório."

#: core/api/pydantic_messages.py:41
msgid "ensure this value contains valid import path or valid callable: {}"
msgstr "Certifique de que o valor contém um caminho de importação válido."

#: core/api/pydantic_messages.py:43
msgid "value is not a valid sequence"
msgstr "O valor não é uma sequência válida."

#: core/api/pydantic_messages.py:44
msgid "value is not a valid list"
msgstr "O valor não é uma lista válida."

#: core/api/pydantic_messages.py:45
msgid "value is not a valid set"
msgstr "O valor não é um conjunto válido."

#: core/api/pydantic_messages.py:46
msgid "value is not a valid frozenset"
msgstr "O valor não é um \"frozenset\" válido."

#: core/api/pydantic_messages.py:47
msgid "value is not a valid tuple"
msgstr "O valor não é uma tupla válida."

#: core/api/pydantic_messages.py:48
msgid "wrong tuple length {}"
msgstr "Tamanho errado de tupla {}."

#: core/api/pydantic_messages.py:50
msgid "ensure this value has at least {} items"
msgstr "Certifique que o valor possui, pelo menos, {} itens."

#: core/api/pydantic_messages.py:53
msgid "ensure this value has at most {} items"
msgstr "Certifique que o valor possui, no máximo, {} itens."

#: core/api/pydantic_messages.py:55
msgid "the list has duplicated items"
msgstr "A lista informada possui itens duplicados."

#: core/api/pydantic_messages.py:57
msgid "ensure this value has at least {} characters"
msgstr "Certifique que o valor possui, pelo menos, {} caracteres."

#: core/api/pydantic_messages.py:60
msgid "ensure this value has at most {} characters"
msgstr "Certifique que o valor possui, no máximo, {} caracteres."

#: core/api/pydantic_messages.py:62
msgid "str type expected"
msgstr "O tipo esperado é \"string\"."

#: core/api/pydantic_messages.py:63
msgid "string does not match regex \"{}\""
msgstr "A \"string\" não corresponde a \"regex\" {}."

#: core/api/pydantic_messages.py:64
msgid "ensure this value is greater than {}"
msgstr "Certifique que o valor é maior que {}."

#: core/api/pydantic_messages.py:66
msgid "ensure this value is greater than or equal to {}"
msgstr "Certifique que o valor é maior ou igual a {}."

#: core/api/pydantic_messages.py:68
msgid "ensure this value is less than {}"
msgstr "Certifique que o valor é menor que {}."

#: core/api/pydantic_messages.py:70
msgid "ensure this value is less than or equal to {}"
msgstr "Certifique que o valor é menor ou igual a {}."

#: core/api/pydantic_messages.py:72
msgid "ensure this value is a multiple of {}"
msgstr "Certifique que o valor é múltiplo de {}."

#: core/api/pydantic_messages.py:73
msgid "value is not a valid decimal"
msgstr "O valor não é um decimal válido."

#: core/api/pydantic_messages.py:75
msgid "ensure that there are no more than {} digits in total"
msgstr "Certifique que não haja mais de {} dígitos."

#: core/api/pydantic_messages.py:78
msgid "ensure that there are no more than {} decimal places"
msgstr "Certifique que não haja mais de {} casas decimais."

#: core/api/pydantic_messages.py:81
msgid "ensure that there are no more than {} digits before the decimal point"
msgstr "Certifique que não haja mais de {} dígitos depois do ponto decimal."

#: core/api/pydantic_messages.py:83
msgid "invalid datetime format"
msgstr "Formato de data e hora inválido."

#: core/api/pydantic_messages.py:84
msgid "invalid date format"
msgstr "Formato de data inválido."

#: core/api/pydantic_messages.py:85
msgid "date is not in the past"
msgstr "Data deve estar no passado."

#: core/api/pydantic_messages.py:86
msgid "date is not in the future"
msgstr "A data deve estar no futuro."

#: core/api/pydantic_messages.py:87
msgid "invalid time format"
msgstr "Formato de hora inválido."

#: core/api/pydantic_messages.py:88
msgid "invalid duration format"
msgstr "Formato de duração inválido."

#: core/api/pydantic_messages.py:89
msgid "value is not a valid hashable"
msgstr "O valor não é um \"hashable\" válido."

#: core/api/pydantic_messages.py:90
msgid "value is not a valid uuid"
msgstr "O valor não é um \"uuid\" válido."

#: core/api/pydantic_messages.py:91
msgid "uuid version {} expected"
msgstr "A versão {} \"uuid\" é necessária."

#: core/api/pydantic_messages.py:92
msgid "instance of {} expected"
msgstr "A instância {} é necessária."

#: core/api/pydantic_messages.py:93
msgid "a class is expected"
msgstr "Uma classe é necessária."

#: core/api/pydantic_messages.py:94
msgid "subclass of {} expected"
msgstr "A subclasse de {} é necessária."

#: core/api/pydantic_messages.py:95
msgid "Invalid JSON"
msgstr "\"JSON\" inválido."

#: core/api/pydantic_messages.py:97
msgid "JSON object must be str, bytes or bytearray"
msgstr "Objeto \"JSON\" deve ser \"string\", \"bytes\" ou \"bytearray\"."

#: core/api/pydantic_messages.py:99
msgid "Invalid regular expression"
msgstr "A expressão regular é inválida."

#: core/api/pydantic_messages.py:101
msgid "instance of {}, tuple or dict expected"
msgstr "Uma instância de {}, tupla ou dicionário é necessária."

#: core/api/pydantic_messages.py:103
msgid "{} is not callable"
msgstr "{} não pode ser chamado. "

#: core/api/pydantic_messages.py:105
msgid "value is not a valid IPv4 or IPv6 address"
msgstr "O valor não é um endereço \"IPv4\" ou \"UPv6\" válido."

#: core/api/pydantic_messages.py:108
msgid "value is not a valid IPv4 or IPv6 interface"
msgstr "O valor não é uma interface \"IPv4\" ou \"UPv6\" válida."

#: core/api/pydantic_messages.py:111
msgid "value is not a valid IPv4 or IPv6 network"
msgstr "O valor não é uma rede \"IPv4\" ou \"UPv6\" válida."

#: core/api/pydantic_messages.py:113
msgid "value is not a valid IPv4 address"
msgstr "O valor não é um endereço \"IPv4\" válido."

#: core/api/pydantic_messages.py:114
msgid "value is not a valid IPv6 address"
msgstr "O valor não é um endereço \"IPv6\" válido."

#: core/api/pydantic_messages.py:115
msgid "value is not a valid IPv4 network"
msgstr "O valor não é uma rede \"IPv4\" válida."

#: core/api/pydantic_messages.py:116
msgid "value is not a valid IPv6 network"
msgstr "O valor não é uma rede \"IPv6\" válida."

#: core/api/pydantic_messages.py:117
msgid "value is not a valid IPv4 interface"
msgstr "O valor não é uma interface \"IPv4\" válida."

#: core/api/pydantic_messages.py:118
msgid "value is not a valid IPv6 interface"
msgstr "O valor não é uma interface \"IPv6\" válida."

#: core/api/pydantic_messages.py:119
msgid "value is not a valid color: {}"
msgstr "O valor não é uma cor válida: {}."

#: core/api/pydantic_messages.py:120
msgid "value is not a valid boolean"
msgstr "O valor não é um boleano válido."

#: core/api/pydantic_messages.py:121
msgid "card number is not all digits"
msgstr "O número do cartão possui dígitos a menos."

#: core/api/pydantic_messages.py:122
msgid "card number is not luhn valid"
msgstr "O cartão não possui um \"luhn\" válido."

#: core/api/pydantic_messages.py:123
msgid "Length for a {}"
msgstr "Tamanho para um {}."

#: core/api/pydantic_messages.py:125
msgid "could not parse value and unit from byte string"
msgstr "Não foi possível converter o valor e unidade de \"byte\" para \"string\"."

#: core/api/pydantic_messages.py:127
msgid "could not interpret byte unit: {}"
msgstr "Não foi possível interpretar a unidade \"byte\": {}."

#: core/api/pydantic_messages.py:128
msgid "Discriminator {} is missing in value"
msgstr "O valor do discriminador {} está faltando."

#: core/api/pydantic_messages.py:129
msgid "No match for discriminator {}"
msgstr "Nenhuma correspondência para o discriminador {}."

#: core/api/routes.py:39
msgid "Unauthorized."
msgstr "Não autorizado."

#: core/api/routes.py:47
msgid "Internationalization works."
msgstr "A internacionalização está funcionando."

#: core/api/schemas.py:13
msgid "Invalid toast variant."
msgstr "Variante de toast inválida."

#: core/websocket.py:57
msgid "Invalid status."
msgstr "Status inválido."

#: friends/tasks.py:21
msgid "Your friend {} just joined ReloadClub!"
msgstr "O seu amigo {} acabou de entrar para a ReloadClub!"

#: lobbies/api/controller.py:204
msgid "Invalid invite id"
msgstr "Convite inválido."

#: lobbies/api/controller.py:219 lobbies/api/controller.py:238
#: lobbies/api/controller.py:255 lobbies/api/controller.py:280
#: lobbies/api/controller.py:311
msgid "We are under maintenance. Try again later."
msgstr "Estamos em manutenção. Tente novamente mais tarde."

#: lobbies/api/controller.py:268
msgid "{} kicked you from lobby."
msgstr "{} removeu você do lobby."

#: lobbies/api/routes.py:55
msgid "Invite must be accepted or refused. Can't be none."
msgstr "Convite precisa ser aceito ou recusado."

#: lobbies/models/invite.py:51 lobbies/models/invite.py:114
#: lobbies/models/lobby.py:473
msgid "Invite not found."
msgstr "Convite não encontrado."

#: lobbies/models/lobby.py:234 lobbies/models/lobby.py:295
#: lobbies/models/lobby.py:425
msgid "User not found."
msgstr "Usuário não encontrado."

#: lobbies/models/lobby.py:239 lobbies/models/lobby.py:304
#: lobbies/models/lobby.py:430
msgid "A verified account is required to perform this action."
msgstr "Uma conta verificada é necessária para realizar esta ação."

#: lobbies/models/lobby.py:243 lobbies/models/lobby.py:308
#: lobbies/models/lobby.py:434
msgid "Offline user."
msgstr "Usuário offline."

#: lobbies/models/lobby.py:246 lobbies/models/lobby.py:535
msgid "The given type is not valid."
msgstr "O tipo informado não é válido."

#: lobbies/models/lobby.py:252 lobbies/models/lobby.py:549
msgid "The given mode is not valid."
msgstr "O modo informado não é válido."

#: lobbies/models/lobby.py:289
msgid "Lobby not found."
msgstr "Lobby não encontrado."

#: lobbies/models/lobby.py:311 lobbies/models/lobby.py:401
#: lobbies/models/lobby.py:485 lobbies/models/lobby.py:512
#: lobbies/models/lobby.py:521 lobbies/models/lobby.py:532
#: lobbies/models/lobby.py:546
msgid "Lobby is queued."
msgstr "Lobby está em fila."

#: lobbies/models/lobby.py:322 lobbies/models/lobby.py:398
msgid "Lobby is full."
msgstr "Lobby está cheio."

#: lobbies/models/lobby.py:418
msgid "Invited user is already a lobby player."
msgstr "Usuário convidado já faz parte do lobby."

#: lobbies/models/lobby.py:421
msgid "User already invited."
msgstr "Usuário já foi convidado."

#: lobbies/models/lobby.py:489
msgid "Can't start queue due to player restriction."
msgstr "Não foi possível iniciar a fila por causa de uma restrição."

#: lobbies/models/lobby.py:555
msgid "Owner cannot be removed."
msgstr "O dono não pode ser removido."

#: lobbies/models/player.py:99
msgid "Player cannot dodge while in queue restriction."
msgstr ""
"Jogador não pode escapar de uma partida enquanto estiver em uma restrição."

#: lobbies/models/player.py:168
msgid "Player not found"
msgstr "Jogador não encontrado."

#: matches/models.py:182
msgid "Unable to finish match while not running."
msgstr "Não é possível finalizar uma partida que não foi iniciada."

#: matches/models.py:193
msgid "Unable to warmup while not loaded."
msgstr ""
"Não é possível iniciar o aquecimento para uma partida que não está pronta."

#: matches/models.py:200
msgid "Unable to start match while not warmed up."
msgstr "Não é possível iniciar uma partida que não está pronta."

#: matches/models.py:209
msgid "Unable to cancel match after is finished."
msgstr "Não é possível cancelar uma partida depois de ser finalizada."

#: notifications/admin.py:33
msgid "Notified users"
msgstr "Usuários notificados"

#: notifications/forms.py:11
msgid "All active users"
msgstr "Usuários ativos"

#: notifications/forms.py:12
msgid "Online users"
msgstr "Usuários online"

#: notifications/models.py:179
msgid "Notification not found."
msgstr "Notificação não encontrada."

#: pre_matches/api/controller.py:86
msgid ""
"All our servers are unavailable at this moment. Please, try again later."
msgstr ""
"Todos os nossos servidores estão indisponíveis no momento. Tente novamente "
"mais tarde."

#: pre_matches/api/controller.py:121
msgid "Can't lock in for a new match while in a match."
msgstr ""
"Não é possível entrar em uma nova partida enquanto estiver em uma partida."

#: pre_matches/api/controller.py:125
msgid "Player already locked in."
msgstr "Jogador já foi marcado como pronto."

#: pre_matches/api/controller.py:151
msgid "Can't ready in for a new match while in a match."
msgstr ""
"Não é possível entrar em uma nova partida enquanto estiver em uma partida."

#: pre_matches/api/controller.py:156
msgid "Player already set as ready."
msgstr "Jogador já foi marcado como pronto."

#: pre_matches/models/pre_match.py:156
msgid "All teams must be ready in order to create a PreMatch."
msgstr "Todos os times precisam estar prontos para criar uma partida."

#: pre_matches/models/pre_match.py:177
msgid "PreMatch not found."
msgstr "Pré partida não encontrada."

#: pre_matches/models/pre_match.py:223
msgid "PreMatch is not ready for ready players."
msgstr ""
"Partida ainda não está pronta para receber pedidos de jogadores prontos."

#: pre_matches/models/pre_match.py:229
msgid "PreMatch is not ready to lock in players."
msgstr ""
"Partida ainda não está pronta para receber pedidos de jogadores a "
"participar."

#: pre_matches/models/team.py:202 pre_matches/models/team.py:215
msgid "Team not found."
msgstr "Time não encontrado."

#: pre_matches/models/team.py:230
msgid "Lobbies have differents types or modes."
msgstr "Os lobbies tem modos ou tipos diferentes."

#: pre_matches/models/team.py:233
msgid "Team players count exceeded."
msgstr "A quantidade de jogadores em time foi excedida."

#: pre_matches/models/team.py:247 pre_matches/models/team.py:271
msgid "Lobby already on a team."
msgstr "O lobby já está em um time."

#: pre_matches/models/team.py:251 pre_matches/models/team.py:275
msgid "Lobby not queued."
msgstr "Lobby não está em fila."

#: pre_matches/tasks.py:45
msgid ""
"Some players in your lobby were not ready before thetimer ran out and the "
"match was cancelled. The recurrenceof this conduct may result in "
"restrictions."
msgstr ""
"Alguns jogadores no seu lobby não ficaram prontos antes do tempo acabar e a "
"partida foi cancelada. A recorrência dessa conduta pode resultar em "
"restrições."

#: store/models.py:136
msgid "The total sum of items on this box cannot be greater then 100%."
msgstr "A soma total dos itens da caixa não podem ultrapassar 100%"

#: support/api/controller.py:68
msgid "Attachment is too large (max 3MB)."
msgstr "O anexo é muito grande (máx 3MB)."

#: support/api/schemas.py:31
msgid "Invalid ticket subject."
msgstr "Assunto de ticket inválido."

#: support/api/schemas.py:38
msgid "\"report_user_id\" field cannot be blank for this subject."
msgstr "O campo \"report_user_id\" não pode ser vazio para esse tipo de ticket."

#~ msgid "Account"
#~ msgstr "Conta"

#~ msgid "Important Dates"
#~ msgstr "Datas Importantes"

#~ msgid "Statuses"
#~ msgstr "Status"

#~ msgid "Activation"
#~ msgstr "Ativação"

#~ msgid "In hours."
#~ msgstr "Em horas."

#~ msgid "Users aren't friends."
#~ msgstr "Usuários não são amigos."

#~ msgid "Unable to mark match as ready while not loading."
#~ msgstr "Não é possível marcar uma partida que não foi carregada como pronta."
